sudo: true

language: go

go: 
  - 1.9.2

go_import_path: github.com/goharbor/harbor

services: 
  - docker

dist: trusty

matrix:
  include:
  - go: "1.10"
    env:
    - UTTEST=true
  - go: "1.10"
    env:
    - E2ETEST=true

env:
  global:
    - POSTGRESQL_HOST: localhost
    - POSTGRESQL_PORT: 5432
    - POSTGRESQL_USR: postgres
    - POSTGRESQL_PWD: root123
    - POSTGRESQL_DATABASE: registry
    - ADMINSERVER_URL: http://127.0.0.1:8888
    - DOCKER_COMPOSE_VERSION: 1.7.1
    - HARBOR_ADMIN: admin
    - HARBOR_ADMIN_PASSWD: Harbor12345
    - UI_SECRET: tempString
    - KEY_PATH: /data/secretkey
    - REDIS_HOST: localhost
    - REG_VERSION: v2.6.2
    - UI_BUILDER_VERSION: 1.6.0


before_install:
   - sudo ./tests/hostcfg.sh
   - sudo ./tests/generateCerts.sh
   - sudo ./make/prepare
   - sudo mkdir -p "/data/redis"
   - sudo mkdir -p /etc/ui/ca/ && sudo mv ./tests/ca.crt /etc/ui/ca/
   - sudo mkdir -p /harbor && sudo mv ./VERSION /harbor/UIVERSION
   - sudo ./tests/testprepare.sh

install:
   - if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_install.sh ; fi
   - if [ "$E2ETEST" == true ]; then bash ./tests/travis/e2e_install.sh ; fi

before_script:
  - if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_prepare.sh ; else echo 'skipping ui tests'; fi
  # - if [ "$E2ETEST" == true ]; then bash ./tests/travis/e2e_prepare.sh ; else echo 'skipping e2e tests'; fi

script:
  - if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_run.sh ; fi
  - if [ "$E2ETEST" == true ]; then bash ./tests/travis/e2e_run.sh ; fi
