sudo: true
language: go
go:
- 1.9.2
go_import_path: github.com/goharbor/harbor
services:
- docker
dist: trusty
matrix:
  include:
  - go: 1.9.2
    env:
    - UTTEST=false
  - go: 1.9.2
    env:
    - APITEST_DB=true
  - go: 1.9.2
    env:
    - APITEST_LDAP=false
  - go: 1.9.2
    env:
    - OFFLINE=false
env:
  global:
  - POSTGRESQL_HOST: localhost
  - POSTGRESQL_PORT: 5432
  - POSTGRESQL_USR: postgres
  - POSTGRESQL_PWD: root123
  - POSTGRESQL_DATABASE: registry
  - ADMINSERVER_URL: http://127.0.0.1:8888
  - DOCKER_COMPOSE_VERSION: 1.22.0
  - HARBOR_ADMIN: admin
  - HARBOR_ADMIN_PASSWD: Harbor12345
  - CORE_SECRET: tempString
  - KEY_PATH: "/data/secretkey"
  - REDIS_HOST: localhost
  - REG_VERSION: v2.6.2
  - UI_BUILDER_VERSION: 1.6.0
  - secure: bucvUgoe/FWK4/93erpwkvpf4k8RhVIvaFz3RuMrxq0wrnX7m+MyrswfG+Bynv3lbLzFVWaNN98EyYUrRJAvek3DTdF8UZA6+ZvN+21cgkbqkCsCTDOvBLBSIqfYne5jkxmBJEVzeMB+iMXIFTpVFwJ4Jnxz/HEj72Chnqfv0wAt/0IhwsFsuDkFUkmk8gX1z/sPVbG71q8Fw/am5gsfjU21cuIXugp1Z2J2NSxJEjU+EGbLPkt4LJD50pUq2qxpJYldfWiCgiuzES40XVXxvd7S7m3svEYvBh7/IgHKM5Q4zQ55zDmdq2y0QmeWKZJIEXJHplg68qBrxPWaIDE1hZ/0BYhlYBa41gUImlD6RxG8OD6dCJmXOspMAecNol15hWuKTaWfxBEdO7mg2Iqa73wzs7XlbZa0Ry+kIbnE49VJu+WaBwu8UxgDjpti6byvpkovc9fcKhkl2z4T1ZGkPIR2nLxFzzq2Q7x3o36vIf0cz4a8jXRpHzrABXh7mJrdgyqbfHRZSRFOLB6FCz6snyyvtfNyhbZuKQ+qUs5otkA0LSmsFdzI3/Y6b+6kGWwA9f9ITLuzgCj+fBTZrXWqF/msnzTJBx4M12Om5OkFfUVIosOSrBxwU9XIPMqt+nzt217noE+/jeFjBAq34tVDljCscw/syVrN3o7BjYWmjKg=
  - secure: BeauhX9ivvGNLjNnIJAqNL6yZ3r3JV8SzgKg4EsNzMEmqgt8lu5gXYa+n57ie4iZgif6cIJqlCM884g2mEVuulhoEHg0SB0Zp5pS+3SRpGFxp0Fv6YwsrwfNgQ3yc4TDlZvoNNfIur6VmR05MlAGaq+Y0HpeFNMsDXFvOcJCoOR/NCDHSZniY+QSbV1NNLOoifLm0jxKjG36csY1S5GYaFzWBbnJUHxEbPZx3RccyCy8+m2t3ToAYeHuACVeqirUA55k/NidacstHldg/h/TjSS6vqrux2vcU9bJDYc+0bijB73rIc+rYOIOj3tXpQqVFKP0+/VHw+nHLEoOYpbBvDycRYqMGbDk+fdI730hYys2q+kISyy6MEACkOmt0XGcroreNq2A8fMwiM7ctG/4DE5hVLumr+ESGmyXJ1qwSXEUpRW48vPue8pPNag1xuLjtqToivEbiItEBxD7wTJnYmSrNNq36cbk9M+emYBlDMkDc223J0MNwGWKgFc5p6sj7FalvLGa1H7+VDOkh6PsM3gq70oSxykfuBuKnY0j2dYmj/oJfTjUgHo1C45t2RDYqqV20t8tTiuD6Wo/P1WTKPi+Bj/hzn+SN85J8hgK6qZpd2kKtpyZlSF7WYNGnP+LbfY6XQQLgztNn/U1Te/1lWHXGxuiInW+pFQ8nr+P+4k=
  - secure: aII0d3DZ/XIfy4+kGS8lcbiaOousEnC0HXdn7WJu20hNC54pPoEjxhLBJphgHD8lpNsOKCQSmrHf+9TnpDjo99rT8WKcM4Qk7s5R4TxwYt3SFP31gHa+bt18utKGGKeB4IHZfr5ShbRpmCzMpvSO/fmdatnFyxpLA9YasnS3FCA4mfLSCTKw6blwKzDhqzxe0pp0+F2Zo3QZCztSKa6fmfM8XhCYEhcMNpLOY92QQRNHku+7wwItpyJ1UfXchR/R4mOks2fv/gtxrbsbnEJrmbPVW16CL8wNMhsj8ctN1L4pLY/OjYUy3NWL7S4zKZAAYPY6fbgw8JyZ2u/iDPEn9znlsMFS/yyXv/cVMYlRWynOL6h/tTXTl3/C8u1SGxNimBhmRYKQHtJlpmWz4sYprL7Q4y5991in1afpF3O2TJd0BOc/OnGBh77tqoMWHp2J8HsU+4qbVbZvRr9NrE7PfNRL/972AJG0vkT6Z68TqEoVw9fTXmatStvQAwaR4IyVe5HouKOjxXfvY8kbwSXQWJ7apI3FOs7O4ODbYJOI1wie2yh1Vfv21sZG0SIqGP34KjbBpAKBFqxGWRmy5EmeNfufSpGy2KYfuXhUYrfBkU67V2/X6LFXNMbTz9B49E4NUDOGD67A469jDYD1EcJvoJHTYrJm//1GyHCBewU2CV4=
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- IP=`ip addr s eth0 |grep "inet "|awk '{print $2}' |awk -F "/" '{print $1}'`
- sudo sed -i '$a DOCKER_OPTS=\"--insecure-registry '$IP':5000\"' /etc/default/docker
- export IP=$IP
- sudo service docker restart
install:
- if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_install.sh ; fi
- if [ "$APITEST_DB" == true ]; then bash ./tests/travis/api_common_install.sh $IP
  DB; fi
- if [ "$APITEST_LDAP" == true ]; then bash ./tests/travis/api_common_install.sh $IP
  LDAP; fi
script:
- if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_run.sh $IP; fi
- if [ "$APITEST_DB" == true ]; then bash ./tests/travis/api_run.sh DB $IP; fi
- if [ "$APITEST_LDAP" == true ]; then bash ./tests/travis/api_run.sh LDAP $IP; fi
- if [ "$OFFLINE" == true ]; then bash ./tests/travis/distro_installer.sh; fi