sudo: true
language: go
go:
- 1.9.2
go_import_path: github.com/goharbor/harbor
services:
- docker
dist: trusty
matrix:
  include:
  - go: 1.9.2
    env:
    - UTTEST=true
  - go: 1.9.2
    env:
    - APITEST_DB=true
  - go: 1.9.2
    env:
    - APITEST_LDAP=true
  - go: 1.9.2
    env:
    - OFFLINE=true
env:
  global:
  - POSTGRESQL_HOST: localhost
  - POSTGRESQL_PORT: 5432
  - POSTGRESQL_USR: postgres
  - POSTGRESQL_PWD: root123
  - POSTGRESQL_DATABASE: registry
  - ADMINSERVER_URL: http://127.0.0.1:8888
  - DOCKER_COMPOSE_VERSION: 1.22.0
  - HARBOR_ADMIN: admin
  - HARBOR_ADMIN_PASSWD: Harbor12345
  - CORE_SECRET: tempString
  - KEY_PATH: "/data/secretkey"
  - REDIS_HOST: localhost
  - REG_VERSION: v2.6.2
  - UI_BUILDER_VERSION: 1.6.0
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- IP=`ip addr s eth0 |grep "inet "|awk '{print $2}' |awk -F "/" '{print $1}'`
- sudo sed -i '$a DOCKER_OPTS=\"--insecure-registry '$IP':5000\"' /etc/default/docker
- export IP=$IP
- sudo service docker restart
- mkdir -p ./logs
install:
- if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_install.sh ; fi
- if [ "$APITEST_DB" == true ]; then bash ./tests/travis/api_common_install.sh $IP
  DB; fi
- if [ "$APITEST_LDAP" == true ]; then bash ./tests/travis/api_common_install.sh $IP
  LDAP; fi
script:
- if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_run.sh $IP; fi
- if [ "$APITEST_DB" == true ]; then bash ./tests/travis/api_run.sh DB $IP; fi
- if [ "$APITEST_LDAP" == true ]; then bash ./tests/travis/api_run.sh LDAP $IP; fi
- if [ "$OFFLINE" == true ]; then bash ./tests/travis/distro_installer.sh; fi

deploy:
  provider: gcs
  access_key_id: GOOGWEBABXMTTRAJCGSG2BZF
  secret_access_key:
    secure: cPCFFVnlX/2Wwbs2idUPMpH9fMOpavR66gkWyhiIqPKT97kwXGjLyr1FYBpm/gzFsY72MFJC9pZsVm6kKo9yf/O9W3rgy+/xn8uoHY+lhHZ7Jd+u3s7SbpYf6XZXnOcSmDTQzX+XrcjKmxj8P+kQsPJBnxwPs2wYo5hAoIWGez6bLZ45+z8UpFdRwyNSk6q4nsybK1psLrYRpUD3oScexVZjtEco1En/95aJDhSONWHPdleY0DEZxBXRwCWmNOtiKTGkOVfqbHhBuWzmctJwJIJudaq5NYlZ8citWQb7BsnT2bOWOrMAyaFiLujBM1IQYeJfdbpNQWmCctKuIZFLq/9nnhQRWAYVJIMwSzU3PJ6LcAvax34coTQ3MF3iElFOXiTwqsLOlAtacnQBt1tAo1f6WcrrCuEvZl0aXdGv9jxnXrxOd3rwRo836QFwI9zjCZITlsHuukxzi76r50S4j93R+hPYm8/o/JKD5mIuvstDcW7oafTVIUFCbA0AuPhEmKGqBrkJL9Ar6mr5Q72OSd/oFZqkcQY3TllM1iZkBfuXWS2iRG7iProkh4xAF2FMQesdRqCCfrTfh3UYn3F4srBxQt8fQ0ZcL+/rdSp38ctHy3vtu8d/S9b1RajVe1F/afQNYH0Fg+Wrts240GhKiuQl+FZ8UZRFQdoUSxtykf4=
  bucket: "harbor-ci-logs"
  acl: public-read
  local-dir: logs