FROM photon:2.0

#Source0:        http://ftp.postgresql.org/pub/source/v%{version}/%{name}-%{version}.tar.bz2
#%define sha1    postgresql=e24333824d361968958613f546ae06011d9d1dfc
# Common libraries needed

ENV PG_MAJOR 9.6
ENV PG_VERSION 9.6.21
ENV PG_SHA256 930feaef28885c97ec40c26ab6221903751eeb625de92b22602706d7d47d1634

RUN tdnf install -y sed krb5-devel libxml2-devel openldap perl readline-devel
    openssl-devel \
    zlib-devel \
    tzdata \
    krb5 \
    libxml2 \
    openldap \
    openssl \
    readline \
    zlib \
    tzdata \
    postgresql-libs \
    postgresql-devel \
    && tdnf clean all

RUN set -eux; \
        \
        wget -O postgresql.tar.bz2 "https://ftp.postgresql.org/pub/source/v$PG_VERSION/postgresql-$PG_VERSION.tar.bz2"; \
        echo "$PG_SHA256 *postgresql.tar.bz2" | sha256sum -c -; \
        mkdir -p /usr/src/postgresql; \
        tar -xf postgresql.tar.bz2 -C /usr/src/postgresql --strip-components 1; \
        rm postgresql.tar.bz2; \
        cd /usr/src/postgresql;

RUN  sed -i '/DEFAULT_PGSOCKET_DIR/s@/tmp@/run/postgresql@' src/include/pg_config_manual.h &&
        ./configure \
            --enable-thread-safety \
            --prefix=%{_prefix} \
            --with-ldap \
            --with-libxml \
            --with-openssl \
            --with-gssapi \
            --with-readline
