// Code generated by mockery v2.1.0. DO NOT EDIT.

package dao

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/goharbor/harbor/src/common/models"

	q "github.com/goharbor/harbor/src/lib/q"
)

// DAO is an autogenerated mock type for the DAO type
type DAO struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, query
func (_m *DAO) Count(ctx context.Context, query *q.Query) (int64, error) {
	ret := _m.Called(ctx, query)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *q.Query) int64); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *q.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, n
func (_m *DAO) Create(ctx context.Context, n *models.NotificationJob) (int64, error) {
	ret := _m.Called(ctx, n)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *models.NotificationJob) int64); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.NotificationJob) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DAO) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByPolicyID provides a mock function with given fields: ctx, policyID
func (_m *DAO) DeleteByPolicyID(ctx context.Context, policyID int64) error {
	ret := _m.Called(ctx, policyID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, policyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *DAO) Get(ctx context.Context, id int64) (*models.NotificationJob, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.NotificationJob
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.NotificationJob); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NotificationJob)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastTriggerJobsGroupByEventType provides a mock function with given fields: ctx, policyID
func (_m *DAO) GetLastTriggerJobsGroupByEventType(ctx context.Context, policyID int64) ([]*models.NotificationJob, error) {
	ret := _m.Called(ctx, policyID)

	var r0 []*models.NotificationJob
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.NotificationJob); ok {
		r0 = rf(ctx, policyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.NotificationJob)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, policyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, query
func (_m *DAO) List(ctx context.Context, query *q.Query) ([]*models.NotificationJob, error) {
	ret := _m.Called(ctx, query)

	var r0 []*models.NotificationJob
	if rf, ok := ret.Get(0).(func(context.Context, *q.Query) []*models.NotificationJob); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.NotificationJob)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *q.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, n, props
func (_m *DAO) Update(ctx context.Context, n *models.NotificationJob, props ...string) error {
	_va := make([]interface{}, len(props))
	for _i := range props {
		_va[_i] = props[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, n)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.NotificationJob, ...string) error); ok {
		r0 = rf(ctx, n, props...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
