// Copyright Project Harbor Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package http

import (
	"crypto/tls"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewServerTLSConfigCurvePreferences(t *testing.T) {
	cfg := NewServerTLSConfig()

	require.NotEmpty(t, cfg.CurvePreferences)
	// the hybrid post-quantum key exchange must stay first so that PQC-capable
	// clients negotiate quantum-resistant key establishment (issue #23709)
	assert.Equal(t, tls.X25519MLKEM768, cfg.CurvePreferences[0])
	// classical fallback for clients without ML-KEM support
	assert.Contains(t, cfg.CurvePreferences, tls.X25519)
	assert.Contains(t, cfg.CurvePreferences, tls.CurveP256)
	assert.Equal(t, uint16(tls.VersionTLS12), cfg.MinVersion)
}

// TestNewServerTLSConfigNegotiatesPQC performs a real loopback handshake and
// verifies that a default Go client (which offers X25519MLKEM768 since Go 1.24)
// actually negotiates the post-quantum hybrid key exchange with the server config.
func TestNewServerTLSConfigNegotiatesPQC(t *testing.T) {
	ts := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	cfg := NewServerTLSConfig()
	// reuse the self-signed certificate generated by httptest
	ts.TLS = cfg
	ts.StartTLS()
	defer ts.Close()

	client := ts.Client()
	res, err := client.Get(ts.URL)
	require.NoError(t, err)
	defer res.Body.Close()

	require.NotNil(t, res.TLS)
	assert.Equal(t, uint16(tls.VersionTLS13), res.TLS.Version)
	assert.Equal(t, tls.X25519MLKEM768, res.TLS.CurveID,
		"a PQC-capable client must negotiate the hybrid post-quantum key exchange")
}
