name: CI
env:
   POSTGRESQL_HOST: localhost
   POSTGRESQL_PORT: 5432
   POSTGRESQL_USR: postgres
   POSTGRESQL_PWD: root123
   POSTGRESQL_DATABASE: registry
   DOCKER_COMPOSE_VERSION: 2.27.1
   HARBOR_ADMIN: admin
   HARBOR_ADMIN_PASSWD: Harbor12345
   CORE_SECRET: tempString
   KEY_PATH: "/data/secret/keys/secretkey"
   REDIS_HOST: localhost
   REG_VERSION: v2.7.1-patch-2819-2553
   UI_BUILDER_VERSION: 1.6.0

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'tests/**'
      - '!tests/**.sh'
      - '!tests/apitests/**'
      - '!tests/ci/**'
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'tests/**'
      - '!tests/**.sh'
      - '!tests/apitests/**'
      - '!tests/ci/**'

permissions:
  id-token: write
  contents: read

jobs:

  AWS:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/github.com/goharbor/harbor

      - name: Configure AWS credentials
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p "${HOME}/.aws"
          cat > "${HOME}/.aws/credentials" <<EOF
          [default]
          aws_access_key_id=${AWS_ACCESS_KEY_ID}
          aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
          EOF
          chmod -R go-rwx "${HOME}/.aws"
          ls -la "${HOME}/.aws"
          aws s3 ls
          echo "test" > test.txt
          aws s3 cp test.txt s3://harbor-ci-logs
          aws s3 ls s3://harbor-ci-logs

